import { pdfjsLib } from './pdfjs'
import type { DetectedZone, Lot, PrestationType } from '../types'
import { uid } from '../types'
import { suggestCategories } from '../data/categorize'

/**
 * Detection method (see the "Annexe" tab in the app for the user-facing explanation):
 *
 * The submission PDFs are generated by CAN-type bid software. The lots to source are marked by
 * the preparer using the PDF highlighter tool, which pdf.js exposes as native `Highlight`
 * annotations (subtype "Highlight") with an exact rectangle and RGB color - no pixel sampling
 * needed. Convention: yellow highlight = fourniture seule, any other highlight color =
 * fourniture et pose. A highlight rectangle can be tiny (one header line) or huge (a whole page
 * or more) - the preparer just drags the highlighter down the margin, so the same rectangle
 * commonly covers a chapter header AND all its articles AND unrelated sibling sub-chapters below
 * it. Never assume one highlight == one lot; always resolve each *line* under the rectangle to
 * its own chapter context.
 *
 * CAN documents number every row in the "Pos." column, headers and priced articles alike, all at
 * the same left margin - there is no indentation or literal dashed rule to tell a header apart
 * from a priced position. The one reliable signal is the code's shape:
 *  - A header code has NO decimal point: "500", "540", "R592", "134", "447"... It only ever
 *    carries a title, never a quantity/price. "R"-prefixed codes are the preparer's own custom
 *    additions (the CAN legend prints this explicitly) and must be recognised as headers too.
 *  - A priced article's code always has a decimal point: "511.201", "134.308", "R592.101". Such a
 *    line never changes the current chapter context, it just belongs to it.
 * Headers nest arbitrarily deep with no visual cue ("500 Armatures" > "540 Accessoires
 * d'armature" > "541 Armatures de support" are three consecutive header lines), so the algorithm
 * tracks a single "current chapter" pointer that gets overwritten by *every* header line it sees.
 * By the time a priced (decimal) line is reached, that pointer naturally holds the most specific
 * header above it - which is exactly the lot boundary the preparer intends: siblings like 541,
 * 543, 544, 545, 546 under the same umbrella "540" are distinct lots, while a header with no
 * priced children of its own (500, 540, 430, R590...) never becomes a lot by itself.
 *
 * Lots are grouped by (highlight color, current chapter code) across the *whole* document -
 * several highlighted runs under the same code become one lot; a different code (or a different
 * highlight color, since that changes fourniture vs fourniture+pose) becomes another. The header
 * line itself does not need to be inside the highlighted rectangle for this to work: if only the
 * priced children are highlighted (e.g. "R891 Escaliers..." left white, but R891.100-104
 * highlighted), the chapter pointer was still set when the header line was read, so the children
 * resolve to the right lot regardless.
 *
 * Separately, some preparers drop a `FreeText` annotation (a text box, often boxed in red) next
 * to a chapter instead of highlighting it - typically a logistics note ("livraison groupée ~800m3
 * pour les 2 soumissions") that applies to the whole chapter rather than one article. Whenever
 * such a note is found, the nearest enclosing "round" chapter (a code ending in "00", e.g. "500"
 * or "600" - the level *above* the fine-grained per-sibling lots described above) becomes its own
 * lot, spanning every page until the next round-numbered chapter starts. Fourniture seule by
 * default; this only encodes one confirmed real-world example and may need revisiting once more
 * cases turn up.
 */

interface TextLine {
  y: number
  xStart: number
  text: string
  items: { x: number; y: number }[]
}

interface ChapterKey {
  code: string
  title: string
}

const NONDECIMAL_HEADER_RE = /^((?:R)?\d{2,3})\s+[A-ZÀ-Þ]/
const DECIMAL_ARTICLE_RE = /^(?:R)?\d{2,3}\.\d+\b/
const CFC_RE = /CFC:\s*([\d.]+)/
const CAN_CHAPTER_RE = /CAN Construction\s*:\s*(\d+)/
const CAN_CHAPTER_TITLE_RE = /CAN Construction\s*:\s*\d+\s+(.+?)\s+[A-Z]\/\d+\(/
const BANNER_RE = /^(Projet|Contrat|Objets|Page|Soumission)\s*:/

function groupLines(items: Array<{ str: string; transform: number[] }>): TextLine[] {
  const list = items
    .filter((it) => it.str.trim().length > 0)
    .map((it) => ({ str: it.str, x: it.transform[4], y: it.transform[5] }))
  list.sort((a, b) => (Math.abs(a.y - b.y) < 3 ? a.x - b.x : b.y - a.y))
  const lines: { y: number; items: { str: string; x: number; y: number }[] }[] = []
  for (const it of list) {
    let line = lines.find((l) => Math.abs(l.y - it.y) < 3)
    if (!line) {
      line = { y: it.y, items: [] }
      lines.push(line)
    }
    line.items.push(it)
  }
  lines.sort((a, b) => b.y - a.y)
  return lines.map((line) => {
    line.items.sort((a, b) => a.x - b.x)
    return {
      y: line.y,
      xStart: Math.min(...line.items.map((i) => i.x)),
      text: line.items.map((i) => i.str).join(' ').replace(/\s+/g, ' ').trim(),
      items: line.items.map((i) => ({ x: i.x, y: i.y })),
    }
  })
}

interface RawHighlight {
  kind: 'L0' | 'article'
  color: 'jaune' | 'autre'
  code: string
  title: string
  /** The round (x00) chapter this run sits under, e.g. "600" for a run coded "612" - used to
   *  tell apart a genuine lot from highlighter spillover into a chapter a FreeText note already
   *  claims whole (see the filter right after the main page loop below). */
  roundCode: string
  pages: number[]
  cfc: string
  text: string
}

interface RawNote {
  code: string
  title: string
  pages: number[]
  cfc: string
  text: string
}

export interface AnalyzeResult {
  zones: DetectedZone[]
  lots: Lot[]
  numPages: number
}

/**
 * Some submission PDFs (flattened exports, chapters pasted in as screenshots/scans) carry no
 * selectable text at all - every character is drawn as a vector outline or baked into a raster
 * image. Native analysis can't read chapter/CFC banners from such a page, so callers should check
 * this first and fall back to the OCR pipeline (analyzeOcr.ts) when it returns false.
 */
export async function pdfHasExtractableText(data: ArrayBuffer): Promise<boolean> {
  const doc = await pdfjsLib.getDocument({ data: data.slice(0) }).promise
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p)
    const textContent = await page.getTextContent()
    if (textContent.items.some((it) => 'str' in it && it.str.trim().length > 0)) return true
  }
  return false
}

export async function analyzeSubmissionPdf(data: ArrayBuffer): Promise<AnalyzeResult> {
  const doc = await pdfjsLib.getDocument({ data: data.slice(0) }).promise

  const pageBodyLines = new Map<number, TextLine[]>()
  const pageAllLines = new Map<number, TextLine[]>()
  const pageCfc = new Map<number, string>()
  const pageCanChapter = new Map<number, string>()
  const pageCanChapterTitle = new Map<number, string>()
  const pageHighlightAnnots = new Map<number, Array<{ color: Uint8ClampedArray; rect: number[] }>>()
  const pageNoteAnnots = new Map<number, Array<{ rect: number[]; contents: string }>>()
  // For every body line, the chapter header code/title active at that point (the "current
  // chapter" pointer described above), plus the coarser "round" (x00) chapter for FreeText notes.
  const pageLineChapters = new Map<
    number,
    Array<{ line: TextLine; key: ChapterKey | null; roundKey: ChapterKey | null }>
  >()
  const pageRoundKeyAtEnd = new Map<number, ChapterKey | null>()

  let prevPageLastLine: string | null = null
  let currentKey: ChapterKey | null = null
  let currentRoundKey: ChapterKey | null = null
  let currentChapterForKeys: string | undefined

  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p)
    const [annots, textContent] = await Promise.all([page.getAnnotations(), page.getTextContent()])
    const lines = groupLines(textContent.items as Array<{ str: string; transform: number[] }>)
    pageAllLines.set(p, lines)

    const bannerText = lines.slice(0, 6).map((l) => l.text).join(' ')
    const cfcMatch = bannerText.match(CFC_RE)
    if (cfcMatch) pageCfc.set(p, cfcMatch[1])
    const canMatch = bannerText.match(CAN_CHAPTER_RE)
    if (canMatch) pageCanChapter.set(p, canMatch[1])
    const canTitleMatch = bannerText.match(CAN_CHAPTER_TITLE_RE)
    if (canTitleMatch) pageCanChapterTitle.set(p, canTitleMatch[1].trim())

    const bodyLines = lines.filter((l) => !BANNER_RE.test(l.text) && l.y < 775)
    pageBodyLines.set(p, bodyLines)

    const marginCandidates = bodyLines.filter((l) => !/^R\b/.test(l.text))
    const marginX = marginCandidates.length ? Math.min(...marginCandidates.map((l) => l.xStart)) : null

    if (pageCanChapter.get(p) !== currentChapterForKeys) {
      currentKey = null
      currentRoundKey = null
      currentChapterForKeys = pageCanChapter.get(p)
    }

    const endedWithAReporter = prevPageLastLine !== null && /^A reporter\s*:/.test(prevPageLastLine)
    const lineChapters: Array<{ line: TextLine; key: ChapterKey | null; roundKey: ChapterKey | null }> = []
    bodyLines.forEach((line, idx) => {
      if (!(idx === 0 && endedWithAReporter)) {
        const m = line.text.match(NONDECIMAL_HEADER_RE)
        if (m && marginX !== null && Math.abs(line.xStart - marginX) < 6) {
          const code = m[1]
          const title = line.text.slice(m[0].length - 1).trim()
          currentKey = { code, title }
          if (Number(code.replace(/^R/, '')) % 100 === 0) currentRoundKey = { code, title }
        }
      }
      lineChapters.push({ line, key: currentKey, roundKey: currentRoundKey })
    })
    pageLineChapters.set(p, lineChapters)
    pageRoundKeyAtEnd.set(p, currentRoundKey)
    prevPageLastLine = bodyLines.length ? bodyLines[bodyLines.length - 1].text : prevPageLastLine

    const typedAnnots = annots as Array<{
      subtype: string
      color?: Uint8ClampedArray
      rect: number[]
      contents?: string
    }>
    pageHighlightAnnots.set(
      p,
      typedAnnots
        .filter((a) => a.subtype === 'Highlight' && a.color)
        .map((a) => ({ color: a.color as Uint8ClampedArray, rect: a.rect })),
    )
    pageNoteAnnots.set(
      p,
      typedAnnots
        .filter((a) => a.subtype === 'FreeText')
        .map((a) => ({ rect: a.rect, contents: (a.contents ?? '').trim() })),
    )
  }

  function chapterPageRange(startPage: number): number {
    const chapter = pageCanChapter.get(startPage)
    let last = startPage
    for (let p = startPage + 1; p <= doc.numPages; p++) {
      if (pageCanChapter.get(p) === chapter) last = p
      else break
    }
    return last
  }

  /** Last page (from startPage) for which `code` is still the active "round" chapter. */
  function roundKeyPageRange(startPage: number, code: string): number {
    let last = startPage
    let sawIt = false
    for (let p = startPage; p <= doc.numPages; p++) {
      if (pageCanChapter.get(p) !== pageCanChapter.get(startPage)) break
      const chapters = pageLineChapters.get(p) ?? []
      let brokeOnThisPage = false
      for (const c of chapters) {
        if (c.roundKey?.code === code) {
          sawIt = true
          last = p
        } else if (sawIt) {
          brokeOnThisPage = true
          break
        }
      }
      if (brokeOnThisPage) break
    }
    return last
  }

  let highlights: RawHighlight[] = []
  const notes: RawNote[] = []

  for (let p = 1; p <= doc.numPages; p++) {
    const bodyLines = pageBodyLines.get(p) ?? []
    const allLines = pageAllLines.get(p) ?? []
    const chapters = pageLineChapters.get(p) ?? []
    const isChapterStartPage = pageCanChapter.get(p) !== undefined && pageCanChapter.get(p) !== pageCanChapter.get(p - 1)
    const firstBodyLine = bodyLines[0]
    const cfc = pageCfc.get(p) ?? ''

    for (const h of pageHighlightAnnots.get(p) ?? []) {
      const [rx0, ry0, rx1, ry1] = h.rect
      const contained = chapters.filter(({ line }) =>
        line.items.some((it) => it.x >= rx0 - 3 && it.x <= rx1 + 3 && it.y >= ry0 - 3 && it.y <= ry1 + 3),
      )
      const isYellow = h.color[0] > 200 && h.color[1] > 200 && h.color[2] < 100
      const color: 'jaune' | 'autre' = isYellow ? 'jaune' : 'autre'

      let isL0 = false
      if (isChapterStartPage && contained.length === 0) {
        isL0 = allLines.some((l) => l.y >= 760 && l.y >= ry0 - 3 && l.y <= ry1 + 3)
      } else if (isChapterStartPage && contained.length > 0 && firstBodyLine) {
        isL0 = Math.abs(contained[0].line.y - firstBodyLine.y) < 3
      }

      if (isL0) {
        const endPage = chapterPageRange(p)
        highlights.push({
          kind: 'L0',
          color,
          code: pageCanChapter.get(p) ?? '',
          title: pageCanChapterTitle.get(p) ?? '',
          roundCode: '',
          pages: Array.from({ length: endPage - p + 1 }, (_, i) => p + i),
          cfc,
          text: pageCanChapterTitle.get(p) ?? '',
        })
        continue
      }

      if (contained.length === 0) continue

      // Contained lines are already in top-to-bottom document order (groupLines sorts that way).
      // Split them into consecutive runs that share the same chapter code, one highlight entry
      // per run. A run is dropped if it has no chapter context yet (shouldn't normally happen),
      // or if it never reaches a priced (decimal-coded) line - a run that's just a header title
      // (and maybe its intro paragraph) before the code changes again is a pure umbrella chapter,
      // never a lot on its own (see "500 Armatures" / "540 Accessoires d'armature" in the header
      // comment above).
      let runStart = 0
      for (let i = 1; i <= contained.length; i++) {
        const sameAsPrev = i < contained.length && contained[i].key?.code === contained[runStart].key?.code
        if (sameAsPrev) continue
        const run = contained.slice(runStart, i)
        const key = run[0].key
        const hasPricedLine = run.some((r) => DECIMAL_ARTICLE_RE.test(r.line.text.trim()))
        if (key && hasPricedLine) {
          highlights.push({
            kind: 'article',
            color,
            code: key.code,
            title: key.title,
            roundCode: run[0].roundKey?.code ?? '',
            pages: [p],
            cfc,
            text: run.map((r) => r.line.text).join(' '),
          })
        }
        runStart = i
      }
    }

    for (const note of pageNoteAnnots.get(p) ?? []) {
      const [, , , ny1] = note.rect
      let roundKey: ChapterKey | null = null
      for (const c of chapters) {
        if (c.line.y >= ny1 - 3) roundKey = c.roundKey
        else break
      }
      if (!roundKey) roundKey = pageRoundKeyAtEnd.get(p - 1) ?? null
      if (!roundKey) continue

      const endPage = roundKeyPageRange(p, roundKey.code)
      notes.push({
        code: roundKey.code,
        title: roundKey.title,
        pages: Array.from({ length: Math.max(endPage - p + 1, 1) }, (_, i) => p + i),
        cfc,
        text: note.contents,
      })
    }
  }

  // A FreeText note already claims its whole round chapter as one lot. Drop any highlight run
  // that sits under that same round chapter - in practice this is over-drawn highlighter
  // spilling from an adjacent, unrelated chapter (the noted chapter itself is never colour-
  // highlighted, since the preparer used a note instead), not a deliberate finer-grained lot
  // inside the noted chapter. Matched by chapter ancestry, not by page number: the noted chapter
  // and its neighbours often share a page (e.g. one ends and the next begins mid-page).
  const notedRoundCodes = new Set(notes.map((n) => n.code))
  highlights = highlights.filter((h) => !notedRoundCodes.has(h.roundCode))

  // ---- Build zones (one per highlight run / note, for display and traceability) ----
  const zones: DetectedZone[] = [
    ...highlights.map((h) => ({
      id: uid(),
      page: h.pages[0],
      chapterCode: h.code,
      chapterTitle: h.title,
      subChapterCode: '',
      subChapterTitle: '',
      cfcCode: h.cfc,
      text: h.text,
      color: h.color,
    })),
    ...notes.map((n) => ({
      id: uid(),
      page: n.pages[0],
      chapterCode: n.code,
      chapterTitle: n.title,
      subChapterCode: '',
      subChapterTitle: '',
      cfcCode: n.cfc,
      text: n.text || n.title,
      color: 'jaune' as const,
    })),
  ]

  // ---- Build lots: group highlight runs by (color, chapter code) across the whole document ----
  interface LotGroup {
    color: 'jaune' | 'autre'
    code: string
    title: string
    cfc: string
    pages: Set<number>
    zoneIds: string[]
    textSample: string
  }
  const lotGroups = new Map<string, LotGroup>()

  highlights.forEach((h, idx) => {
    const zoneId = zones[idx].id
    const key = `${h.color}|${h.code}`
    const existing = lotGroups.get(key)
    if (existing) {
      h.pages.forEach((pg) => existing.pages.add(pg))
      existing.zoneIds.push(zoneId)
      if (existing.textSample.length < 800) existing.textSample += ' ' + h.text.slice(0, 200)
    } else {
      lotGroups.set(key, {
        color: h.color,
        code: h.code,
        title: h.title,
        cfc: h.cfc,
        pages: new Set(h.pages),
        zoneIds: [zoneId],
        textSample: h.text.slice(0, 200),
      })
    }
  })

  const lots: Lot[] = Array.from(lotGroups.values()).map((g): Lot => {
    const title = `${g.code} ${g.title}`
    const categories = suggestCategories(`${title} ${g.textSample}`)
    return {
      id: uid(),
      title,
      cfcCode: g.cfc,
      chapterCode: g.code,
      chapterTitle: g.title,
      subChapterCode: '',
      subChapterTitle: '',
      prestationType: (g.color === 'jaune' ? 'fourniture' : 'fourniture_pose') as PrestationType,
      pages: Array.from(g.pages).sort((a, b) => a - b),
      positionCount: g.zoneIds.length,
      zoneIds: g.zoneIds,
      validated: false,
      categories,
      suppliers: [],
      followUp: [],
    }
  })

  notes.forEach((n, idx) => {
    const zoneId = zones[highlights.length + idx].id
    const title = `${n.code} ${n.title}`
    lots.push({
      id: uid(),
      title,
      cfcCode: n.cfc,
      chapterCode: n.code,
      chapterTitle: n.title,
      subChapterCode: '',
      subChapterTitle: '',
      prestationType: 'fourniture',
      pages: n.pages,
      positionCount: 1,
      zoneIds: [zoneId],
      validated: false,
      categories: suggestCategories(`${title} ${n.text}`),
      suppliers: [],
      followUp: [],
    })
  })

  lots.sort((a, b) => a.pages[0] - b.pages[0])

  return { zones, lots, numPages: doc.numPages }
}
