import { pdfjsLib } from './pdfjs'
import type { DetectedZone, Lot, PrestationType } from '../types'
import { uid } from '../types'

/**
 * Detection method (see the "Annexe" tab in the app for the user-facing explanation):
 *
 * The submission PDFs are generated by CAN-type bid software. The lots to source are marked by
 * the preparer using the PDF highlighter tool, which pdf.js exposes as native `Highlight`
 * annotations (subtype "Highlight") with an exact rectangle and RGB color - no pixel sampling
 * needed. Convention: yellow highlight = fourniture seule, any other highlight color =
 * fourniture et pose.
 *
 * Each CAN page repeats a banner "CAN Construction : <code> <title> ..." — a change in <code>
 * between two consecutive pages marks the start of a new CAN chapter. Within a chapter, section
 * headers are printed at the leftmost column of the page as "<number> <Title>" (capitalized).
 * We track the closest preceding header line for each highlight to label the corresponding lot.
 *
 * If a highlight covers the chapter's own banner/title line instead of a body article, the
 * preparer means "the whole chapter is one lot" (typically for chapters handed to a single
 * specialised subcontractor, e.g. précontrainte, éléments préfabriqués) - in that case we expand
 * the lot to the full page range of that CAN chapter.
 */

interface TextLine {
  y: number
  xStart: number
  text: string
  items: { x: number; y: number }[]
}

const HEADER_RE = /^(\d{2,3}(?:\.\d+)?)\s+[A-ZÀ-Þ]/
const CFC_RE = /CFC:\s*([\d.]+)/
const CAN_CHAPTER_RE = /CAN Construction\s*:\s*(\d+)/
const CAN_CHAPTER_TITLE_RE = /CAN Construction\s*:\s*\d+\s+(.+?)\s+[A-Z]\/\d+\(/
const BANNER_RE = /^(Projet|Contrat|Objets|Page|Soumission)\s*:/

function groupLines(items: Array<{ str: string; transform: number[] }>): TextLine[] {
  const list = items
    .filter((it) => it.str.trim().length > 0)
    .map((it) => ({ str: it.str, x: it.transform[4], y: it.transform[5] }))
  list.sort((a, b) => (Math.abs(a.y - b.y) < 3 ? a.x - b.x : b.y - a.y))
  const lines: { y: number; items: { str: string; x: number; y: number }[] }[] = []
  for (const it of list) {
    let line = lines.find((l) => Math.abs(l.y - it.y) < 3)
    if (!line) {
      line = { y: it.y, items: [] }
      lines.push(line)
    }
    line.items.push(it)
  }
  lines.sort((a, b) => b.y - a.y)
  return lines.map((line) => {
    line.items.sort((a, b) => a.x - b.x)
    return {
      y: line.y,
      xStart: Math.min(...line.items.map((i) => i.x)),
      text: line.items.map((i) => i.str).join(' ').replace(/\s+/g, ' ').trim(),
      items: line.items.map((i) => ({ x: i.x, y: i.y })),
    }
  })
}

interface HeaderEvent {
  page: number
  y: number
  code: string
  title: string
}

interface RawHighlight {
  page: number
  color: 'jaune' | 'autre'
  rect: [number, number, number, number]
  header: { code: string; title: string } | null
  cfc: string | null
  isChapterLot: boolean
  text: string
}

export interface AnalyzeResult {
  zones: DetectedZone[]
  lots: Lot[]
  numPages: number
}

export async function analyzeSubmissionPdf(data: ArrayBuffer): Promise<AnalyzeResult> {
  const loadingTask = pdfjsLib.getDocument({ data: data.slice(0) })
  const doc = await loadingTask.promise

  // ---- Pass 1: collect per-page lines, header events, CAN chapter banners ----
  const pageBodyLines = new Map<number, TextLine[]>()
  const pageAllLines = new Map<number, TextLine[]>()
  const pageCfc = new Map<number, string>()
  const pageCanChapter = new Map<number, string>()
  const pageCanChapterTitle = new Map<number, string>()
  const pageAnnots = new Map<number, Array<{ color: Uint8ClampedArray; rect: number[] }>>()
  const headerEvents: HeaderEvent[] = []
  let prevPageLastLine: string | null = null

  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p)
    const [annots, textContent] = await Promise.all([page.getAnnotations(), page.getTextContent()])
    const lines = groupLines(textContent.items as Array<{ str: string; transform: number[] }>)
    pageAllLines.set(p, lines)

    const bannerText = lines.slice(0, 6).map((l) => l.text).join(' ')
    const cfcMatch = bannerText.match(CFC_RE)
    if (cfcMatch) pageCfc.set(p, cfcMatch[1])
    const canMatch = bannerText.match(CAN_CHAPTER_RE)
    if (canMatch) pageCanChapter.set(p, canMatch[1])
    const canTitleMatch = bannerText.match(CAN_CHAPTER_TITLE_RE)
    if (canTitleMatch) pageCanChapterTitle.set(p, canTitleMatch[1].trim())

    const bodyLines = lines.filter((l) => !BANNER_RE.test(l.text) && l.y < 775)
    pageBodyLines.set(p, bodyLines)

    const marginCandidates = bodyLines.filter((l) => !/^R\b/.test(l.text))
    const marginX = marginCandidates.length ? Math.min(...marginCandidates.map((l) => l.xStart)) : null

    const endedWithAReporter = prevPageLastLine !== null && /^A reporter\s*:/.test(prevPageLastLine)
    bodyLines.forEach((line, idx) => {
      if (idx === 0 && endedWithAReporter) return
      const m = line.text.match(HEADER_RE)
      if (m && marginX !== null && Math.abs(line.xStart - marginX) < 6) {
        headerEvents.push({ page: p, y: line.y, code: m[1], title: line.text.slice(m[0].length - 1).trim() })
      }
    })
    prevPageLastLine = bodyLines.length ? bodyLines[bodyLines.length - 1].text : prevPageLastLine

    pageAnnots.set(
      p,
      (annots as Array<{ subtype: string; color?: Uint8ClampedArray; rect: number[] }>)
        .filter((a) => a.subtype === 'Highlight' && a.color)
        .map((a) => ({ color: a.color as Uint8ClampedArray, rect: a.rect })),
    )
  }

  function headerBefore(page: number, y: number): { code: string; title: string } | null {
    let found: HeaderEvent | null = null
    for (const ev of headerEvents) {
      if (ev.page > page) break
      if (ev.page === page && ev.y < y) break
      found = ev
    }
    return found ? { code: found.code, title: found.title } : null
  }

  // ---- Pass 2: assign each highlight annotation to a header/lot context ----
  const highlights: RawHighlight[] = []
  for (let p = 1; p <= doc.numPages; p++) {
    const bodyLines = pageBodyLines.get(p) ?? []
    const allLines = pageAllLines.get(p) ?? []
    const annots = pageAnnots.get(p) ?? []
    const isChapterStartPage = pageCanChapter.get(p) !== undefined && pageCanChapter.get(p) !== pageCanChapter.get(p - 1)
    const firstBodyLine = bodyLines[0]

    for (const h of annots) {
      const [rx0, ry0, rx1, ry1] = h.rect
      const contained = bodyLines
        .filter((l) => l.items.some((it) => it.x >= rx0 - 3 && it.x <= rx1 + 3 && it.y >= ry0 - 3 && it.y <= ry1 + 3))
        .sort((a, b) => b.y - a.y)
      const text = contained.map((l) => l.text).join(' ')
      const isYellow = h.color[0] > 200 && h.color[1] > 200 && h.color[2] < 100
      const topY = contained.length ? contained[0].y : ry1

      let isChapterLot = Boolean(
        isChapterStartPage && contained.length > 0 && firstBodyLine && Math.abs(topY - firstBodyLine.y) < 3,
      )
      let bannerHit = false
      if (!isChapterLot && isChapterStartPage && contained.length === 0) {
        bannerHit = allLines.some((l) => l.y >= 760 && l.y >= ry0 - 3 && l.y <= ry1 + 3)
        if (bannerHit) isChapterLot = true
      }

      const header = bannerHit
        ? { code: pageCanChapter.get(p) ?? '', title: pageCanChapterTitle.get(p) ?? '' }
        : headerBefore(p, topY)

      highlights.push({
        page: p,
        color: isYellow ? 'jaune' : 'autre',
        rect: h.rect as [number, number, number, number],
        header,
        cfc: pageCfc.get(p) ?? null,
        isChapterLot,
        text: bannerHit ? pageCanChapterTitle.get(p) ?? '' : text,
      })
    }
  }

  // ---- Build zones (one per highlight annotation) ----
  const zones: DetectedZone[] = highlights.map((h) => ({
    id: uid(),
    page: h.page,
    chapterCode: h.header?.code ?? '',
    chapterTitle: h.header?.title ?? '',
    cfcCode: h.cfc ?? '',
    text: h.text,
    color: h.color,
  }))

  // ---- Build lots: group by (page, color, header.code), except chapter-wide highlights ----
  const lotGroups = new Map<
    string,
    { page: number; color: 'jaune' | 'autre'; header: { code: string; title: string } | null; cfc: string | null; zoneIds: string[] }
  >()
  const chapterLotKeys = new Map<string, Lot>()

  highlights.forEach((h, idx) => {
    const zoneId = zones[idx].id
    if (h.isChapterLot) {
      const chapterCode = pageCanChapter.get(h.page) ?? h.header?.code ?? ''
      let endPage = h.page
      for (let p = h.page + 1; p <= doc.numPages; p++) {
        if (pageCanChapter.get(p) === chapterCode) endPage = p
        else break
      }
      const key = `chapter|${chapterCode}|${h.color}`
      const existing = chapterLotKeys.get(key)
      if (existing) {
        existing.zoneIds.push(zoneId)
      } else {
        const pages = Array.from({ length: endPage - h.page + 1 }, (_, i) => h.page + i)
        chapterLotKeys.set(key, {
          id: uid(),
          title: `${h.header?.code ?? ''} ${h.header?.title ?? ''}`.trim(),
          cfcCode: h.cfc ?? '',
          chapterRef: chapterCode,
          prestationType: (h.color === 'jaune' ? 'fourniture' : 'fourniture_pose') as PrestationType,
          pages,
          positionCount: 1,
          zoneIds: [zoneId],
          validated: false,
          categories: [],
          suppliers: [],
          followUp: [],
        })
      }
      return
    }
    const key = `${h.page}|${h.color}|${h.header?.code ?? ''}`
    const existing = lotGroups.get(key)
    if (existing) {
      existing.zoneIds.push(zoneId)
    } else {
      lotGroups.set(key, { page: h.page, color: h.color, header: h.header, cfc: h.cfc, zoneIds: [zoneId] })
    }
  })

  const lots: Lot[] = [
    ...Array.from(lotGroups.values()).map(
      (g): Lot => ({
        id: uid(),
        title: `${g.header?.code ?? ''} ${g.header?.title ?? ''}`.trim() || `Page ${g.page}`,
        cfcCode: g.cfc ?? '',
        chapterRef: g.header?.code ?? '',
        prestationType: (g.color === 'jaune' ? 'fourniture' : 'fourniture_pose') as PrestationType,
        pages: [g.page],
        positionCount: g.zoneIds.length,
        zoneIds: g.zoneIds,
        validated: false,
        categories: [],
        suppliers: [],
        followUp: [],
      }),
    ),
    ...Array.from(chapterLotKeys.values()).map((lot) => ({ ...lot, positionCount: lot.zoneIds.length })),
  ]

  lots.sort((a, b) => a.pages[0] - b.pages[0])

  return { zones, lots, numPages: doc.numPages }
}
