import { pdfjsLib } from './pdfjs'
import type { DetectedZone, Lot, PrestationType } from '../types'
import { uid } from '../types'
import { suggestCategories } from '../data/categorize'

/**
 * Detection method (see the "Annexe" tab in the app for the user-facing explanation):
 *
 * The submission PDFs are generated by CAN-type bid software. The lots to source are marked by
 * the preparer using the PDF highlighter tool, which pdf.js exposes as native `Highlight`
 * annotations (subtype "Highlight") with an exact rectangle and RGB color - no pixel sampling
 * needed. Convention: yellow highlight = fourniture seule, any other highlight color =
 * fourniture et pose. A highlight rectangle can be tiny (one header line) or huge (a whole page
 * or more) - the preparer just drags the highlighter down the margin, so the same rectangle
 * commonly covers a chapter header AND all its articles AND unrelated sibling sub-chapters below
 * it. Never assume one highlight == one lot; always resolve each *line* under the rectangle to
 * its own chapter context.
 *
 * CAN documents number every row in the "Pos." column, headers and priced articles alike, all at
 * the same left margin - there is no indentation or literal dashed rule to tell a header apart
 * from a priced position. The one reliable signal is the code's shape:
 *  - A header code has NO decimal point: "500", "540", "R592", "134", "447"... It only ever
 *    carries a title, never a quantity/price. "R"-prefixed codes are the preparer's own custom
 *    additions (the CAN legend prints this explicitly) and must be recognised as headers too.
 *  - A priced article's code always has a decimal point: "511.201", "134.308", "R592.101". Such a
 *    line never changes the current chapter context, it just belongs to it.
 * Headers nest arbitrarily deep with no visual cue ("500 Armatures" > "540 Accessoires
 * d'armature" > "541 Armatures de support" are three consecutive header lines), so the algorithm
 * tracks a single "current chapter" pointer that gets overwritten by *every* header line it sees.
 * By the time a priced (decimal) line is reached, that pointer naturally holds the most specific
 * header above it - which is exactly the lot boundary the preparer intends: siblings like 541,
 * 543, 544, 545, 546 under the same umbrella "540" are distinct lots, while a header with no
 * priced children of its own (500, 540, 430, R590...) never becomes a lot by itself.
 *
 * Lots are grouped by (highlight color, current chapter code) across the *whole* document -
 * several highlighted runs under the same code become one lot; a different code (or a different
 * highlight color, since that changes fourniture vs fourniture+pose) becomes another. The header
 * line itself does not need to be inside the highlighted rectangle for this to work: if only the
 * priced children are highlighted (e.g. "R891 Escaliers..." left white, but R891.100-104
 * highlighted), the chapter pointer was still set when the header line was read, so the children
 * resolve to the right lot regardless.
 *
 * Separately, some preparers drop a `FreeText` annotation (a text box, often boxed in red) next
 * to a chapter instead of highlighting it - typically a logistics note ("livraison groupée ~800m3
 * pour les 2 soumissions") that applies to the whole chapter rather than one article. Whenever
 * such a note is found, the nearest enclosing "round" chapter (a code ending in "00", e.g. "500"
 * or "600" - the level *above* the fine-grained per-sibling lots described above) becomes its own
 * lot, spanning every page until the next round-numbered chapter starts. Fourniture seule by
 * default; this only encodes one confirmed real-world example and may need revisiting once more
 * cases turn up.
 *
 * Different bid-software vendors/bureaux export CAN documents with the same underlying structure
 * but different surface conventions - each confirmed on real submissions, not hypothetical:
 *  - Chapter codes are usually 2-3 digits, but a bureau numbering by CFC sub-position (e.g.
 *    "1100 ARMATURE", "1110 Fourniture et pose d'acier B500B") uses 4 digits - same header rule,
 *    just a wider digit count.
 *  - One bureau (Thomas Jundt) numbers chapters "N.00" (e.g. "1.00 Fourniture et pose des piliers
 *    béton") and its priced articles "N.01", "N.02"... - i.e. *every* code has a decimal point,
 *    and the header/article distinction is the ".00" suffix specifically, not "has a dot at all".
 *    Recognised as an alternate header shape; a priced-article code is still anything decimal
 *    that ISN'T "x.00", so "1.01" already satisfies the normal article check once the digit-count
 *    bound below is widened to allow a 1-digit prefix.
 *  - Some bureaux print an article's code in full ("532.001") only the first time or right after a
 *    page break, and drop the chapter prefix on every following position on the same page
 *    ("541 Armatures de support." followed by ".200", ".203", ".204"... instead of "541.200",
 *    "541.203"...). Such an orphan code never carries a chapter prefix to match against, so it
 *    can't be told apart from a bare sub-heading by shape alone - the reliable signal instead is
 *    that every priced row (wherever the quantity/price actually lands, sometimes several
 *    wrapped description lines below the code, or in an "up = <unité> :<zone> <qté> up ...
 *    ...................." tally) ends in a long run of dots, the blank fill for the still-empty
 *    Prix/Montant columns - a bare sub-heading with no quantity never has one. That dot-fill is
 *    checked across the whole highlighted run's text, not just the code's own line.
 *  - The repeating table banner above each chapter's articles ("Pos. Cd. Description...") is
 *    filtered out as boilerplate, but its exact wording differs by bureau ("Pos. Libellé U.
 *    Quant. P.U. Prix", "Article Description des travaux Unité Quantité"...). A banner variant
 *    that isn't recognised doesn't just pollute a zone's text - if its (unrelated) left margin is
 *    lower than the real code column's, it can drag the whole page's computed margin left and
 *    break the alignment check every real header on that page depends on.
 */

interface TextLine {
  y: number
  xStart: number
  text: string
  items: { x: number; y: number }[]
}

interface ChapterKey {
  code: string
  title: string
}

const NONDECIMAL_HEADER_RE = /^((?:R)?\d{2,4})\s+[A-ZÀ-Þ]/
// Alternate header shape used by bureaux that give every code a decimal point ("1.00", "3.00")
// instead of reserving the bare (no-dot) form for headers - see the file-header comment above.
const HEADER_DOT_ZERO_RE = /^((?:R)?\d{1,4})\.00\s+[A-ZÀ-Þ]/
// Prefix widened to 1-4 digits (some bureaux use "1.01" or "1110.101"); a bare ".00" suffix is
// excluded because that's exactly the alternate header shape above, never a priced article.
const DECIMAL_ARTICLE_RE = /^(?:R)?\d{1,4}\.(?!00\b)\d+\b/
// A priced row's Prix/Montant columns are printed blank (to be filled in by hand) as a long run
// of dots - "................. ................." or "up = kg ... .......... .........." - the
// one signal that survives even when the code itself is an orphan ".NNN" with no chapter prefix
// to match DECIMAL_ARTICLE_RE against (see file-header comment). A bare sub-heading with no
// quantity/price never has this.
const PRICE_ROW_RE = /\.{4,}/
// The highlight-containment check below tolerates a few points of slop (antialiasing/rounding),
// which occasionally lets the trailing dot-fill of an unrelated PREVIOUS chapter's last line leak
// into the next highlight a hair above it - always a bare zone tag ("COMMUN 4 ..."), never real
// position content. Requiring some actual text before the dots (not just a short tag) is enough
// to tell that stray leak apart from a genuine priced line, which always carries its code and/or
// description alongside the dot-fill.
const MIN_PRICE_ROW_CONTENT = 15
// A running chapter subtotal ("300 Total Alimentation, évacuation, télécommunication ....") is
// printed at the same left margin as a real header and also ends in a dot-fill - matches both
// NONDECIMAL_HEADER_RE and, now, PRICE_ROW_RE, but it's a summary row, not a lot boundary or a
// priced position. Filtered out like the other page boilerplate below.
const TOTAL_ROW_RE = /^(?:R)?\d{2,4}\s+Total\b/
const CFC_RE = /CFC:\s*([\d.]+)/
const CAN_CHAPTER_RE = /CAN Construction\s*:\s*(\d+)/
const CAN_CHAPTER_TITLE_RE = /CAN Construction\s*:\s*\d+\s+(.+?)\s+[A-Z]\/\d+\(/
const BANNER_RE = /^(Projet|Contrat|Objets|Page|Soumission|Chapitre)\s*:/
// Page-footer boilerplate (software name, printer, pagination like "Page 27 de 40", or a bureau's
// own "Imprimé le <date>" export stamp) - not submission content, but ordinary body text with no
// colon, so BANNER_RE above doesn't catch it. A highlight rectangle dragged too far down a page
// routinely oversteps into this line; it must never be treated as part of a lot's text, and must
// never break up a run mid-chapter. Critically, it also sits at the page's true left margin or
// lower (often the lowest text on the page) - left unfiltered, it silently becomes the computed
// marginX and breaks the alignment check for every real header on that page (same failure mode as
// an unrecognised column-header banner, see COLUMN_HEADER_RE below).
const FOOTER_RE = /Page\s+\d+\s+de\s+\d+\s*$|Imprimé\s+le\s+\d/
// The article-table header repeats at the top of every page's article table - same reasoning as
// FOOTER_RE, it just happens to sit a bit lower on the page (below the y < 775 banner cutoff)
// whenever a chapter's table starts partway down a page. Wording varies by bureau/software; an
// unrecognised variant doesn't just leak into a zone's text, it can also drag the page's computed
// left margin (see marginX below) off the real code column and break every header's alignment
// check for that whole page.
const COLUMN_HEADER_RE =
  /^(?:Pos\.\s+Cd\.\s+Description\b|Pos\.\s+Libellé\b|Article\s+Description\s+des\s+travaux\b)/

function groupLines(items: Array<{ str: string; transform: number[] }>): TextLine[] {
  const list = items
    .filter((it) => it.str.trim().length > 0)
    .map((it) => ({ str: it.str, x: it.transform[4], y: it.transform[5] }))
  list.sort((a, b) => (Math.abs(a.y - b.y) < 3 ? a.x - b.x : b.y - a.y))
  const lines: { y: number; items: { str: string; x: number; y: number }[] }[] = []
  for (const it of list) {
    let line = lines.find((l) => Math.abs(l.y - it.y) < 3)
    if (!line) {
      line = { y: it.y, items: [] }
      lines.push(line)
    }
    line.items.push(it)
  }
  lines.sort((a, b) => b.y - a.y)
  return lines.map((line) => {
    line.items.sort((a, b) => a.x - b.x)
    return {
      y: line.y,
      xStart: Math.min(...line.items.map((i) => i.x)),
      text: line.items.map((i) => i.str).join(' ').replace(/\s+/g, ' ').trim(),
      items: line.items.map((i) => ({ x: i.x, y: i.y })),
    }
  })
}

interface RawHighlight {
  kind: 'L0' | 'article'
  color: 'jaune' | 'autre'
  code: string
  title: string
  /** The round (x00) chapter this run sits under, e.g. "600" for a run coded "612" - used to
   *  tell apart a genuine lot from highlighter spillover into a chapter a FreeText note already
   *  claims whole (see the filter right after the main page loop below). */
  roundCode: string
  pages: number[]
  cfc: string
  text: string
}

interface RawNote {
  code: string
  title: string
  pages: number[]
  cfc: string
  text: string
}

export interface AnalyzeResult {
  zones: DetectedZone[]
  lots: Lot[]
  numPages: number
}

/**
 * Some submission PDFs (flattened exports, chapters pasted in as screenshots/scans) carry no
 * selectable text at all - every character is drawn as a vector outline or baked into a raster
 * image. Native analysis can't read chapter/CFC banners from such a page, so callers should check
 * this first and fall back to the OCR pipeline (analyzeOcr.ts) when it returns false.
 */
export async function pdfHasExtractableText(data: ArrayBuffer): Promise<boolean> {
  const doc = await pdfjsLib.getDocument({ data: data.slice(0) }).promise
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p)
    const textContent = await page.getTextContent()
    if (textContent.items.some((it) => 'str' in it && it.str.trim().length > 0)) return true
  }
  return false
}

export async function analyzeSubmissionPdf(data: ArrayBuffer): Promise<AnalyzeResult> {
  const doc = await pdfjsLib.getDocument({ data: data.slice(0) }).promise

  const pageBodyLines = new Map<number, TextLine[]>()
  const pageAllLines = new Map<number, TextLine[]>()
  const pageCfc = new Map<number, string>()
  const pageCanChapter = new Map<number, string>()
  const pageCanChapterTitle = new Map<number, string>()
  const pageHighlightAnnots = new Map<number, Array<{ color: Uint8ClampedArray; rect: number[] }>>()
  const pageNoteAnnots = new Map<number, Array<{ rect: number[]; contents: string }>>()
  // For every body line, the chapter header code/title active at that point (the "current
  // chapter" pointer described above), plus the coarser "round" (x00) chapter for FreeText notes.
  const pageLineChapters = new Map<
    number,
    Array<{ line: TextLine; key: ChapterKey | null; roundKey: ChapterKey | null }>
  >()
  const pageRoundKeyAtEnd = new Map<number, ChapterKey | null>()

  let prevPageLastLine: string | null = null
  let currentKey: ChapterKey | null = null
  let currentRoundKey: ChapterKey | null = null
  let currentChapterForKeys: string | undefined

  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p)
    const [annots, textContent] = await Promise.all([page.getAnnotations(), page.getTextContent()])
    const lines = groupLines(textContent.items as Array<{ str: string; transform: number[] }>)
    pageAllLines.set(p, lines)

    const bannerText = lines.slice(0, 6).map((l) => l.text).join(' ')
    const cfcMatch = bannerText.match(CFC_RE)
    if (cfcMatch) pageCfc.set(p, cfcMatch[1])
    const canMatch = bannerText.match(CAN_CHAPTER_RE)
    if (canMatch) pageCanChapter.set(p, canMatch[1])
    const canTitleMatch = bannerText.match(CAN_CHAPTER_TITLE_RE)
    if (canTitleMatch) pageCanChapterTitle.set(p, canTitleMatch[1].trim())

    const bodyLines = lines.filter(
      (l) =>
        !BANNER_RE.test(l.text) &&
        !FOOTER_RE.test(l.text) &&
        !COLUMN_HEADER_RE.test(l.text) &&
        !TOTAL_ROW_RE.test(l.text) &&
        l.y < 775,
    )
    pageBodyLines.set(p, bodyLines)

    const marginCandidates = bodyLines.filter((l) => !/^R\b/.test(l.text))
    const marginX = marginCandidates.length ? Math.min(...marginCandidates.map((l) => l.xStart)) : null

    if (pageCanChapter.get(p) !== currentChapterForKeys) {
      currentKey = null
      currentRoundKey = null
      currentChapterForKeys = pageCanChapter.get(p)
    }

    const endedWithAReporter = prevPageLastLine !== null && /^A reporter\s*:/.test(prevPageLastLine)
    const lineChapters: Array<{ line: TextLine; key: ChapterKey | null; roundKey: ChapterKey | null }> = []
    bodyLines.forEach((line, idx) => {
      if (!(idx === 0 && endedWithAReporter)) {
        const m = line.text.match(NONDECIMAL_HEADER_RE) ?? line.text.match(HEADER_DOT_ZERO_RE)
        if (m && marginX !== null && Math.abs(line.xStart - marginX) < 6) {
          const code = m[1]
          const title = line.text.slice(m[0].length - 1).trim()
          currentKey = { code, title }
          if (Number(code.replace(/^R/, '')) % 100 === 0) currentRoundKey = { code, title }
        }
      }
      lineChapters.push({ line, key: currentKey, roundKey: currentRoundKey })
    })
    pageLineChapters.set(p, lineChapters)
    pageRoundKeyAtEnd.set(p, currentRoundKey)
    prevPageLastLine = bodyLines.length ? bodyLines[bodyLines.length - 1].text : prevPageLastLine

    const typedAnnots = annots as Array<{
      subtype: string
      color?: Uint8ClampedArray
      rect: number[]
      contents?: string
    }>
    pageHighlightAnnots.set(
      p,
      typedAnnots
        .filter((a) => a.subtype === 'Highlight' && a.color)
        .map((a) => ({ color: a.color as Uint8ClampedArray, rect: a.rect })),
    )
    pageNoteAnnots.set(
      p,
      typedAnnots
        .filter((a) => a.subtype === 'FreeText')
        .map((a) => ({ rect: a.rect, contents: (a.contents ?? '').trim() })),
    )
  }

  function chapterPageRange(startPage: number): number {
    const chapter = pageCanChapter.get(startPage)
    let last = startPage
    for (let p = startPage + 1; p <= doc.numPages; p++) {
      if (pageCanChapter.get(p) === chapter) last = p
      else break
    }
    return last
  }

  /** Last page (from startPage) for which `code` is still the active "round" chapter. */
  function roundKeyPageRange(startPage: number, code: string): number {
    let last = startPage
    let sawIt = false
    for (let p = startPage; p <= doc.numPages; p++) {
      if (pageCanChapter.get(p) !== pageCanChapter.get(startPage)) break
      const chapters = pageLineChapters.get(p) ?? []
      let brokeOnThisPage = false
      for (const c of chapters) {
        if (c.roundKey?.code === code) {
          sawIt = true
          last = p
        } else if (sawIt) {
          brokeOnThisPage = true
          break
        }
      }
      if (brokeOnThisPage) break
    }
    return last
  }

  let highlights: RawHighlight[] = []
  const notes: RawNote[] = []
  // Header-only runs (see below) are never lots by themselves, but their title carries real
  // information ("R592 Poteaux métalliques.") that a bare priced line ("Type: RRW 120x120x6,3
  // S355...") doesn't. Keep that text per chapter code and prepend it to the next priced run
  // under the same code, even if that run is a different highlight annotation on a later page -
  // exactly the case where the header sits alone at the bottom of one page and its articles start
  // on the next.
  const pendingHeaderText = new Map<string, string>()

  for (let p = 1; p <= doc.numPages; p++) {
    const bodyLines = pageBodyLines.get(p) ?? []
    const allLines = pageAllLines.get(p) ?? []
    const chapters = pageLineChapters.get(p) ?? []
    const isChapterStartPage = pageCanChapter.get(p) !== undefined && pageCanChapter.get(p) !== pageCanChapter.get(p - 1)
    const firstBodyLine = bodyLines[0]
    const cfc = pageCfc.get(p) ?? ''

    for (const h of pageHighlightAnnots.get(p) ?? []) {
      const [rx0, ry0, rx1, ry1] = h.rect
      const contained = chapters.filter(({ line }) =>
        line.items.some((it) => it.x >= rx0 - 3 && it.x <= rx1 + 3 && it.y >= ry0 - 3 && it.y <= ry1 + 3),
      )
      const isYellow = h.color[0] > 200 && h.color[1] > 200 && h.color[2] < 100
      const color: 'jaune' | 'autre' = isYellow ? 'jaune' : 'autre'

      let isL0 = false
      if (isChapterStartPage && contained.length === 0) {
        isL0 = allLines.some((l) => l.y >= 760 && l.y >= ry0 - 3 && l.y <= ry1 + 3)
      } else if (isChapterStartPage && contained.length > 0 && firstBodyLine) {
        isL0 = Math.abs(contained[0].line.y - firstBodyLine.y) < 3
      }

      if (isL0) {
        const endPage = chapterPageRange(p)
        highlights.push({
          kind: 'L0',
          color,
          code: pageCanChapter.get(p) ?? '',
          title: pageCanChapterTitle.get(p) ?? '',
          roundCode: '',
          pages: Array.from({ length: endPage - p + 1 }, (_, i) => p + i),
          cfc,
          text: pageCanChapterTitle.get(p) ?? '',
        })
        continue
      }

      if (contained.length === 0) continue

      // Contained lines are already in top-to-bottom document order (groupLines sorts that way).
      // Split them into consecutive runs that share the same chapter code, one highlight entry
      // per run. A run is dropped if it has no chapter context yet (shouldn't normally happen),
      // or if it never reaches a priced (decimal-coded) line - a run that's just a header title
      // (and maybe its intro paragraph) before the code changes again is a pure umbrella chapter,
      // never a lot on its own (see "500 Armatures" / "540 Accessoires d'armature" in the header
      // comment above). Its text isn't lost though - see pendingHeaderText above.
      let runStart = 0
      for (let i = 1; i <= contained.length; i++) {
        const sameAsPrev = i < contained.length && contained[i].key?.code === contained[runStart].key?.code
        if (sameAsPrev) continue
        const run = contained.slice(runStart, i)
        const key = run[0].key
        const runText = run.map((r) => r.line.text).join(' ')
        const dotIndex = runText.search(PRICE_ROW_RE)
        const hasPriceRowWithContent =
          dotIndex > 0 && runText.slice(0, dotIndex).replace(/\s+/g, '').length >= MIN_PRICE_ROW_CONTENT
        const hasPricedLine =
          run.some((r) => DECIMAL_ARTICLE_RE.test(r.line.text.trim())) || hasPriceRowWithContent
        if (key && hasPricedLine) {
          const pending = pendingHeaderText.get(key.code)
          highlights.push({
            kind: 'article',
            color,
            code: key.code,
            title: key.title,
            roundCode: run[0].roundKey?.code ?? '',
            pages: [p],
            cfc,
            text: pending ? `${pending} ${runText}` : runText,
          })
          pendingHeaderText.delete(key.code)
        } else if (key) {
          pendingHeaderText.set(key.code, `${pendingHeaderText.get(key.code) ?? ''} ${runText}`.trim())
        }
        runStart = i
      }
    }

    for (const note of pageNoteAnnots.get(p) ?? []) {
      const [, , , ny1] = note.rect
      let roundKey: ChapterKey | null = null
      for (const c of chapters) {
        if (c.line.y >= ny1 - 3) roundKey = c.roundKey
        else break
      }
      if (!roundKey) roundKey = pageRoundKeyAtEnd.get(p - 1) ?? null
      if (!roundKey) continue

      const endPage = roundKeyPageRange(p, roundKey.code)
      notes.push({
        code: roundKey.code,
        title: roundKey.title,
        pages: Array.from({ length: Math.max(endPage - p + 1, 1) }, (_, i) => p + i),
        cfc,
        text: note.contents,
      })
    }
  }

  // A FreeText note only means "this whole round chapter is a lot" when that chapter has at most
  // one distinct highlighted code of its own - exactly the "600 Béton" case, where the only
  // colour under "600" is a single-position sliver ("612") bled in from the previous chapter's
  // over-drawn highlighter, and the preparer left a note instead of highlighting anything real.
  // When the round chapter has several distinct highlighted codes (e.g. "800" already has R891,
  // R892, R894, R898, each its own genuine multi-position lot), the highlighting is clearly
  // deliberate and a small note nearby (e.g. "Variante préfa" next to one article) is a side
  // remark on that content, not a chapter-wide instruction - keep the fine-grained lots and drop
  // the note instead of the other way around.
  const highlightCodesByRound = new Map<string, Set<string>>()
  for (const h of highlights) {
    if (!h.roundCode) continue
    const set = highlightCodesByRound.get(h.roundCode) ?? new Set<string>()
    set.add(h.code)
    highlightCodesByRound.set(h.roundCode, set)
  }
  const wholeChapterNotes = notes.filter((n) => (highlightCodesByRound.get(n.code)?.size ?? 0) < 2)
  const wholeChapterNoteCodes = new Set(wholeChapterNotes.map((n) => n.code))
  highlights = highlights.filter((h) => !wholeChapterNoteCodes.has(h.roundCode))

  // ---- Build zones (one per highlight run / note, for display and traceability) ----
  const zones: DetectedZone[] = [
    ...highlights.map((h) => ({
      id: uid(),
      page: h.pages[0],
      chapterCode: h.code,
      chapterTitle: h.title,
      subChapterCode: '',
      subChapterTitle: '',
      cfcCode: h.cfc,
      text: h.text,
      color: h.color,
    })),
    ...wholeChapterNotes.map((n) => ({
      id: uid(),
      page: n.pages[0],
      chapterCode: n.code,
      chapterTitle: n.title,
      subChapterCode: '',
      subChapterTitle: '',
      cfcCode: n.cfc,
      text: n.text || n.title,
      color: 'jaune' as const,
    })),
  ]

  // ---- Build lots: group highlight runs by (color, chapter code) across the whole document ----
  interface LotGroup {
    color: 'jaune' | 'autre'
    code: string
    title: string
    cfc: string
    pages: Set<number>
    zoneIds: string[]
    textSample: string
  }
  const lotGroups = new Map<string, LotGroup>()

  highlights.forEach((h, idx) => {
    const zoneId = zones[idx].id
    const key = `${h.color}|${h.code}`
    const existing = lotGroups.get(key)
    if (existing) {
      h.pages.forEach((pg) => existing.pages.add(pg))
      existing.zoneIds.push(zoneId)
      if (existing.textSample.length < 800) existing.textSample += ' ' + h.text.slice(0, 200)
    } else {
      lotGroups.set(key, {
        color: h.color,
        code: h.code,
        title: h.title,
        cfc: h.cfc,
        pages: new Set(h.pages),
        zoneIds: [zoneId],
        textSample: h.text.slice(0, 200),
      })
    }
  })

  const lots: Lot[] = Array.from(lotGroups.values()).map((g): Lot => {
    const title = `${g.code} ${g.title}`
    const categories = suggestCategories(`${title} ${g.textSample}`)
    return {
      id: uid(),
      title,
      cfcCode: g.cfc,
      chapterCode: g.code,
      chapterTitle: g.title,
      subChapterCode: '',
      subChapterTitle: '',
      prestationType: (g.color === 'jaune' ? 'fourniture' : 'fourniture_pose') as PrestationType,
      pages: Array.from(g.pages).sort((a, b) => a - b),
      positionCount: g.zoneIds.length,
      zoneIds: g.zoneIds,
      validated: false,
      categories,
      suppliers: [],
      followUp: [],
    }
  })

  wholeChapterNotes.forEach((n, idx) => {
    const zoneId = zones[highlights.length + idx].id
    const title = `${n.code} ${n.title}`
    lots.push({
      id: uid(),
      title,
      cfcCode: n.cfc,
      chapterCode: n.code,
      chapterTitle: n.title,
      subChapterCode: '',
      subChapterTitle: '',
      prestationType: 'fourniture',
      pages: n.pages,
      positionCount: 1,
      zoneIds: [zoneId],
      validated: false,
      categories: suggestCategories(`${title} ${n.text}`),
      suppliers: [],
      followUp: [],
    })
  })

  lots.sort((a, b) => a.pages[0] - b.pages[0])

  return { zones, lots, numPages: doc.numPages }
}
